config/routes.rb
Rails.application.routes.draw do
  get 'stocks/search'
  devise_for :models
  root 'home#index'
  get 'my_portfolio', to:'models#my_portfolio'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/stock.rb
class Stock < ApplicationRecord
  def self.look_up(ticker_sym)
    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_client[:api_key_p],
      secret_token: Rails.application.credentials.iex_client[:api_key_s],
      endpoint: 'https://cloud.iexapis.com/v1'
    )

      begin
      new(ticker: ticker_sym,name: client.company(ticker_sym).company_name, last_price: client.price(ticker_sym))
        rescue => exception
          return nil?

      end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_model!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  def my_portfolio
      @stock=Stock.look_up(params[:stock])

    render 'models/my_portfolio'
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/home/index.html.erb
<h1>Welcome to Finance Tracker App</h1>
<p>Find me in app/views/home/index.html.erb</p>
<%=link_to 'SignOut', destroy_model_session_path, data: {turbo_method: :delete} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'partials/navigation' %>

    <div class="container">
      <%=render 'partials/warningsanderrors' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/models/my_portfolio.html.erb
<h1 class="mt-5">Portfolio</h1>

<div class="container">
  <h3 class="mt-4">Search Stocks</h3>
  <%= form_tag '#', method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9">
        <%=text_field_tag  :stock, params[:stock], placeholder: "Stock Ticker Symbol", autofocus: true,class: "form-control form-control-lg"%>
      </div>
      <div class="col-sm-3">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon 'search 2x'%>
        <%end %>
      </div>
    </div>
  <% end %>
</div>
<% if @stock %>
<div class="card card-header mt-3">
  <strong>Symbol: </strong><%=@stock.ticker %>

  <strong>Name: </strong><%=@stock.name %>

  <strong>Price: </strong><%=@stock.last_price %>
</div>
<%end %>

app/views/partials/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/partials/_warningsanderrors.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong ><%=notice %></strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <strong><%=alert%></strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/stocks/search.html.erb
<h1>Stocks#search</h1>
<p>Find me in app/views/stocks/search.html.erb</p>